In [1]:
import pandas as pd

In [2]:
series = pd.Series([1,2,3,4,5]) #tạo 1 series
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [3]:
#thay vì như mảng là chỉ mục là các số thì series có thể tùy ý đặt tên cho chỉ mục mong muốn
series = pd.Series([1,2,3,4,5], index=['a','b','c','d','c'])
print(series)

a    1
b    2
c    3
d    4
c    5
dtype: int64


In [4]:
print(series[2])

3


In [6]:
print(series['c'])

c    3
c    5
dtype: int64


In [7]:
print(series[2:]) 
print(series.iloc[2:])

c    3
d    4
c    5
dtype: int64
c    3
d    4
c    5
dtype: int64


In [8]:
dates1 = pd.date_range('20190525', periods=12)
# tạo 1 dãy ngày liên tiếp bắt đầu từ 25 và kéo dài 12 ngày
print(dates1)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[ns]', freq='D')


In [9]:
series = pd.Series([1,2,3,4,5,6,7,8,9,10,11,12])
series.index = dates1 #lấy chuỗi dates1 tạo trước đó gán làm chỉ mục
print(series)

2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64


In [10]:
dates2 = pd.date_range('2019-05-01', periods=12, freq='M')
#giá trị freq là chỉ tần suất ngày cuối cùng của tháng
print(dates2)

DatetimeIndex(['2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31',
               '2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30'],
              dtype='datetime64[ns]', freq='M')


In [11]:
#nếu muốn ngày bắt đầu của tháng thì đặt giá trị freq="MS"
dates2 = pd.date_range('2019-05-01', periods=12, freq='MS')
print(dates2)

DatetimeIndex(['2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01',
               '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01',
               '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01'],
              dtype='datetime64[ns]', freq='MS')


In [13]:
#lưu ý định dang yyyy-dd-MM

In [14]:
#ngoài cài đặt ngày thì có thể cài đặt thêm giờ
dates3 = pd.date_range('2019/05/17 09:00:00', periods=8, freq='H')
#tần suất freq='H' mỗi ngày chênh nhau 1 giờ
print(dates3)

DatetimeIndex(['2019-05-17 09:00:00', '2019-05-17 10:00:00',
               '2019-05-17 11:00:00', '2019-05-17 12:00:00',
               '2019-05-17 13:00:00', '2019-05-17 14:00:00',
               '2019-05-17 15:00:00', '2019-05-17 16:00:00'],
              dtype='datetime64[ns]', freq='H')


In [15]:
#63 khung dữ liệu cấu trúc DataFrame

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.DataFrame(np.random.randn(10,4), 
columns=list('ABCD'))
#tạo ma trận 2 chiều 10 hàng 4 cột, tên các cột nằm trong list
#giá trị trung bình là 0 xoay quanh độ lệch 1
print(df)

          A         B         C         D
0  0.756357 -1.482774 -1.625920  0.084161
1 -1.076687 -1.266881 -0.900162 -1.272279
2 -1.405621  0.743820 -2.384769  1.122924
3 -0.247678  0.060031 -2.408409  0.117069
4 -0.437599 -0.550319 -1.066857  0.386376
5  2.097616  0.269024 -0.407725 -0.341558
6  0.290844 -0.551249  1.026737  1.409417
7  0.653839  1.233693  0.509402  0.978697
8  1.062862  2.069812 -1.029590 -0.047118
9 -1.005626  0.515990 -0.692431 -0.544852


In [21]:
#df = pd.read_csv('data.csv')

In [6]:
days = pd.date_range('20190525', periods=10)
df.index = days #thêm cột chỉ mục ngày tháng vào
print(df)

                   A         B         C         D
2019-05-25  0.756357 -1.482774 -1.625920  0.084161
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [7]:
#lấy thuộc tính chỉ mục
print(df.index)

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03'],
              dtype='datetime64[ns]', freq='D')


In [24]:
#lấy giá trị

In [8]:
print(df.values)

[[ 0.75635714 -1.48277403 -1.62592006  0.08416055]
 [-1.0766867  -1.26688103 -0.90016229 -1.27227926]
 [-1.40562064  0.74382006 -2.38476926  1.12292414]
 [-0.24767828  0.06003149 -2.40840862  0.11706897]
 [-0.4375986  -0.55031894 -1.0668573   0.38637639]
 [ 2.09761593  0.26902389 -0.40772544 -0.34155828]
 [ 0.29084423 -0.55124908  1.02673709  1.40941685]
 [ 0.65383853  1.23369255  0.50940222  0.97869736]
 [ 1.06286189  2.06981211 -1.02958955 -0.04711752]
 [-1.00562634  0.51599041 -0.69243081 -0.54485156]]


In [9]:
print(df.describe())
#hàm lấy số lương(count), trung bình(mean), tiêu chuẩn độ lêch(std), min, mã và 1 số tiêu chuẩn khác

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.068831   0.104115  -0.897972   0.189284
std     1.103812   1.105720   1.107326   0.819993
min    -1.405621  -1.482774  -2.408409  -1.272279
25%    -0.863619  -0.551017  -1.486154  -0.267948
50%     0.021583   0.164528  -0.964876   0.100615
75%     0.730727   0.686863  -0.478902   0.830617
max     2.097616   2.069812   1.026737   1.409417


In [10]:
print(df.mean(0)) #0 có nghĩa là lấy giá trị trung bình trên 1 cột

A    0.068831
B    0.104115
C   -0.897972
D    0.189284
dtype: float64


In [11]:
print(df.mean(1)) #1 có nghĩa là lấy giá trị trung bình trên 1 hàng

2019-05-25   -0.567044
2019-05-26   -1.129002
2019-05-27   -0.480911
2019-05-28   -0.619747
2019-05-29   -0.417100
2019-05-30    0.404339
2019-05-31    0.543937
2019-06-01    0.843908
2019-06-02    0.513992
2019-06-03   -0.431730
Freq: D, dtype: float64


In [12]:
print(df.head()) #lấy 5 hàng đầu trong khung dữ liệu cấu trúc(dataFrame)

                   A         B         C         D
2019-05-25  0.756357 -1.482774 -1.625920  0.084161
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376


In [13]:
print(df.head(8)) #thêm chỉ số bên trong thì sẽ hiện ra số hàng tương ứng

                   A         B         C         D
2019-05-25  0.756357 -1.482774 -1.625920  0.084161
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-06-01  0.653839  1.233693  0.509402  0.978697


In [14]:
print(df.tail()) #5 hàng cuối

                   A         B         C         D
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [15]:
print(df.tail(8)) #tương tự có thêm chỉ số bên trong như head()

                   A         B         C         D
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [16]:
#68
print(df['A'])
# same as
print(df.A)

2019-05-25    0.756357
2019-05-26   -1.076687
2019-05-27   -1.405621
2019-05-28   -0.247678
2019-05-29   -0.437599
2019-05-30    2.097616
2019-05-31    0.290844
2019-06-01    0.653839
2019-06-02    1.062862
2019-06-03   -1.005626
Freq: D, Name: A, dtype: float64
2019-05-25    0.756357
2019-05-26   -1.076687
2019-05-27   -1.405621
2019-05-28   -0.247678
2019-05-29   -0.437599
2019-05-30    2.097616
2019-05-31    0.290844
2019-06-01    0.653839
2019-06-02    1.062862
2019-06-03   -1.005626
Freq: D, Name: A, dtype: float64


In [17]:
print(df[['A', 'B']]) #lấy theo nhãn cột

                   A         B
2019-05-25  0.756357 -1.482774
2019-05-26 -1.076687 -1.266881
2019-05-27 -1.405621  0.743820
2019-05-28 -0.247678  0.060031
2019-05-29 -0.437599 -0.550319
2019-05-30  2.097616  0.269024
2019-05-31  0.290844 -0.551249
2019-06-01  0.653839  1.233693
2019-06-02  1.062862  2.069812
2019-06-03 -1.005626  0.515990


In [18]:
print(df[2:4]) #lấy theo nhãn hàng

                   A         B         C         D
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069


In [19]:
#tương tự có thể dùng bàng iloc
print(df.iloc[2:4])

                   A         B         C         D
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-28 -0.247678  0.060031 -2.408409  0.117069


In [20]:
print(df.iloc[[2,4]]) #trích xuất hàng cụ thể

                   A         B         C         D
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376


In [21]:
#lưu ý
#print(df[[2,4]]) # error; need to use the iloc indexer

In [22]:
#nếu muốn cắt hàng và cột cụ thể thì phải sử dụng chỉ mục iloc()
print(df.iloc[2:4, 1:4])

                   B         C         D
2019-05-27  0.743820 -2.384769  1.122924
2019-05-28  0.060031 -2.408409  0.117069


In [23]:
print(df.iloc[[2,4], [1,3]])

                   B         D
2019-05-27  0.743820  1.122924
2019-05-29 -0.550319  0.386376


In [24]:
#tóm lại nếu bạn muốn cắt 1 loạt hàng thì có thể dùng luôn df[x:y], tuy nhiên
#nếu muốn lấy hàng hoặc cột cụ thể phải dụng chỉ mục iloc

In [25]:
#ngoài cách dùng chỉ mục số hàng để trích xuất thì có thể dùng nhãn giá trị để gọi

In [30]:
#chú ý: hàm iloc là dùng để truy cập dư liệu dựa trên chỉ số, loc dùng để truy cập dữ 
#liệu dựa trên nhãn

In [26]:
print(df['20190601':'20190603'])

                   A         B         C         D
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [27]:
print(df.loc['20190601':'20190603'])

                   A         B         C         D
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [28]:
print(df.loc['20190601':'20190603', 'A':'C']) #bắt buộc phải dùng loc

                   A         B         C
2019-06-01  0.653839  1.233693  0.509402
2019-06-02  1.062862  2.069812 -1.029590
2019-06-03 -1.005626  0.515990 -0.692431


In [29]:
print(df.loc['20190601']) #trích xuất hàng cụ thể

A    0.653839
B    1.233693
C    0.509402
D    0.978697
Name: 2019-06-01 00:00:00, dtype: float64


In [31]:
print(df.loc[['20190601','20190603']]) # KeyError

                   A         B         C         D
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [32]:
#như đã thấy không thể truy cập ngày và giờ như trên đc


In [33]:
from datetime import datetime
date1 = datetime(2019, 6, 1, 0, 0, 0)
date2 = datetime(2019, 6, 3, 0, 0, 0)
print(df.loc[[date1,date2]])

                   A         B         C         D
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852


In [34]:
#hàng và các cột cụ thể
print(df.loc[date1, ['A','C']])

A    0.653839
C    0.509402
Name: 2019-06-01 00:00:00, dtype: float64


In [35]:
#sử dụng at() để lấy giá trị trong 1 ô cụ thể
from datetime import datetime
d = datetime(2019, 6, 3, 0, 0, 0)
print(df.at[d,'B'])

0.5159904053197463


In [36]:
print(df[(df.A > 0) & (df.B>0)]) #sử dụng toán tử để thống kê tập giá trị

                   A         B         C         D
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-06-02  1.062862  2.069812 -1.029590 -0.047118


In [37]:
#72
print(df.transpose()) #chuyển hàng thành cột, cột thành hàng

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.756357   -1.076687   -1.405621   -0.247678   -0.437599    2.097616   
B   -1.482774   -1.266881    0.743820    0.060031   -0.550319    0.269024   
C   -1.625920   -0.900162   -2.384769   -2.408409   -1.066857   -0.407725   
D    0.084161   -1.272279    1.122924    0.117069    0.386376   -0.341558   

   2019-05-31  2019-06-01  2019-06-02  2019-06-03  
A    0.290844    0.653839    1.062862   -1.005626  
B   -0.551249    1.233693    2.069812    0.515990  
C    1.026737    0.509402   -1.029590   -0.692431  
D    1.409417    0.978697   -0.047118   -0.544852  


In [38]:
print(df.T) #ngoài ra có thể chuyển vị bằng T

   2019-05-25  2019-05-26  2019-05-27  2019-05-28  2019-05-29  2019-05-30  \
A    0.756357   -1.076687   -1.405621   -0.247678   -0.437599    2.097616   
B   -1.482774   -1.266881    0.743820    0.060031   -0.550319    0.269024   
C   -1.625920   -0.900162   -2.384769   -2.408409   -1.066857   -0.407725   
D    0.084161   -1.272279    1.122924    0.117069    0.386376   -0.341558   

   2019-05-31  2019-06-01  2019-06-02  2019-06-03  
A    0.290844    0.653839    1.062862   -1.005626  
B   -0.551249    1.233693    2.069812    0.515990  
C    1.026737    0.509402   -1.029590   -0.692431  
D    1.409417    0.978697   -0.047118   -0.544852  


In [44]:
def checkSeriesOrDataframe(var):
    if isinstance(var, pd.DataFrame):
        return 'Dataframe'
    if isinstance(var, pd.Series):
        return 'Series'

#check kiểu dữ liệu là khung cấu trúc hay là series

In [40]:
print(df.sort_index(axis=0, ascending=False)) #sắp xếp theo chỉ mục(hàng) với chỉ số 0

                   A         B         C         D
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-05-30  2.097616  0.269024 -0.407725 -0.341558
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-05-25  0.756357 -1.482774 -1.625920  0.084161


In [41]:
print(df.sort_index(axis=1, ascending=False)) #sắp xếp theo nhãn cột chỉ số 1

                   D         C         B         A
2019-05-25  0.084161 -1.625920 -1.482774  0.756357
2019-05-26 -1.272279 -0.900162 -1.266881 -1.076687
2019-05-27  1.122924 -2.384769  0.743820 -1.405621
2019-05-28  0.117069 -2.408409  0.060031 -0.247678
2019-05-29  0.386376 -1.066857 -0.550319 -0.437599
2019-05-30 -0.341558 -0.407725  0.269024  2.097616
2019-05-31  1.409417  1.026737 -0.551249  0.290844
2019-06-01  0.978697  0.509402  1.233693  0.653839
2019-06-02 -0.047118 -1.029590  2.069812  1.062862
2019-06-03 -0.544852 -0.692431  0.515990 -1.005626


In [42]:
print(df.sort_values('A', axis=0)) #sắp xếp theo giá trị trên cột A

                   A         B         C         D
2019-05-27 -1.405621  0.743820 -2.384769  1.122924
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-06-03 -1.005626  0.515990 -0.692431 -0.544852
2019-05-29 -0.437599 -0.550319 -1.066857  0.386376
2019-05-28 -0.247678  0.060031 -2.408409  0.117069
2019-05-31  0.290844 -0.551249  1.026737  1.409417
2019-06-01  0.653839  1.233693  0.509402  0.978697
2019-05-25  0.756357 -1.482774 -1.625920  0.084161
2019-06-02  1.062862  2.069812 -1.029590 -0.047118
2019-05-30  2.097616  0.269024 -0.407725 -0.341558


In [43]:
print(df.sort_values('20190601', axis=1)) #sắp xếp theo chỉ mục cụ thể

                   C         A         D         B
2019-05-25 -1.625920  0.756357  0.084161 -1.482774
2019-05-26 -0.900162 -1.076687 -1.272279 -1.266881
2019-05-27 -2.384769 -1.405621  1.122924  0.743820
2019-05-28 -2.408409 -0.247678  0.117069  0.060031
2019-05-29 -1.066857 -0.437599  0.386376 -0.550319
2019-05-30 -0.407725  2.097616 -0.341558  0.269024
2019-05-31  1.026737  0.290844  1.409417 -0.551249
2019-06-01  0.509402  0.653839  0.978697  1.233693
2019-06-02 -1.029590  1.062862 -0.047118  2.069812
2019-06-03 -0.692431 -1.005626 -0.544852  0.515990


In [45]:
#dùng hàm apply để dùng cho giá trị
import math
sq_root = lambda x: math.sqrt(x) if x > 0 else x #định nghĩa 2 hàm
sq = lambda x: x**2

In [46]:
print(df.B.apply(sq_root)) #nếu số dương trên cột B thì lấy căn 2

2019-05-25   -1.482774
2019-05-26   -1.266881
2019-05-27    0.862450
2019-05-28    0.245013
2019-05-29   -0.550319
2019-05-30    0.518675
2019-05-31   -0.551249
2019-06-01    1.110717
2019-06-02    1.438684
2019-06-03    0.718325
Freq: D, Name: B, dtype: float64


In [47]:
print(df.B.apply(sq)) #lấy bình phương giá trị trên cột

2019-05-25    2.198619
2019-05-26    1.604988
2019-05-27    0.553268
2019-05-28    0.003604
2019-05-29    0.302851
2019-05-30    0.072374
2019-05-31    0.303876
2019-06-01    1.521997
2019-06-02    4.284122
2019-06-03    0.266246
Freq: D, Name: B, dtype: float64


In [48]:
#df.apply(sq_root) # ValueError
#vì dối tượng truyền vào lúc này là 1 DataFrame chứ không phải là series

In [50]:
#thay vào đó 
df.apply(sq)

A         B         C         D
2019-05-25  0.572076  2.198619  2.643616  0.007083
2019-05-26  1.159254  1.604988  0.810292  1.618695
2019-05-27  1.975769  0.553268  5.687124  1.260959
2019-05-28  0.061345  0.003604  5.800432  0.013705
2019-05-29  0.191493  0.302851  1.138185  0.149287
2019-05-30  4.399993  0.072374  0.166240  0.116662
2019-05-31  0.084590  0.303876  1.054189  1.986456
2019-06-01  0.427505  1.521997  0.259491  0.957849
2019-06-02  1.129675  4.284122  1.060055  0.002220
2019-06-03  1.011284  0.266246  0.479460  0.296863

In [53]:
#nếu muốn sử dụng sq_root thì hãy duyệt từng cột
for column in df:
    df[column] = df[column].apply(sq_root)
print(df)

                   A         B         C         D
2019-05-25  0.869688 -1.482774 -1.625920  0.290104
2019-05-26 -1.076687 -1.266881 -0.900162 -1.272279
2019-05-27 -1.405621  0.862450 -2.384769  1.059681
2019-05-28 -0.247678  0.245013 -2.408409  0.342153
2019-05-29 -0.437599 -0.550319 -1.066857  0.621592
2019-05-30  1.448315  0.518675 -0.407725 -0.341558
2019-05-31  0.539300 -0.551249  1.013280  1.187189
2019-06-01  0.808603  1.110717  0.713724  0.989291
2019-06-02  1.030952  1.438684 -1.029590 -0.047118
2019-06-03 -1.005626  0.718325 -0.692431 -0.544852


In [54]:
#thực tế thì apply() có thể áp dụng trên hàng hoặc cột cụ thể , tuy nhiên với thư viện numpy thì nó sẽ hiểu trên tất cả
print(df.apply(np.sum, axis=0)) #tổng hợp các giá trị trên mỗi cột

A    0.523647
B    1.042641
C   -8.788859
D    2.284204
dtype: float64


In [55]:
print(df.apply(np.sum, axis=1)) #với hàng

2019-05-25   -1.948902
2019-05-26   -4.516009
2019-05-27   -1.868259
2019-05-28   -2.068920
2019-05-29   -1.433183
2019-05-30    1.217706
2019-05-31    2.188520
2019-06-01    3.622335
2019-06-02    1.392929
2019-06-03   -1.524584
Freq: D, dtype: float64


In [56]:
#thêm và xóa hàng hoặc cột 

In [57]:
import pandas as pd

In [58]:
data = {'name': ['Janet', 'Nad', 'Timothy', 'June', 'Amy'],
'year': [2012, 2012, 2013, 2014, 2014],
'reports': [6, 13, 14, 1, 7]}
df = pd.DataFrame(data, index =
['Singapore', 'China', 'Japan', 'Sweden', 'Norway'])
print(df)

              name  year  reports
Singapore    Janet  2012        6
China          Nad  2012       13
Japan      Timothy  2013       14
Sweden        June  2014        1
Norway         Amy  2014        7


In [59]:
#thêm cột
import numpy as np
schools = np.array(["Cambridge","Oxford","Oxford","Cambridge","Oxford"])
df["school"] = schools
print(df)

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford


In [60]:
print(df.drop(['China', 'Japan'])) #xóa hàng

            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford


In [61]:
print(df[df.name != 'Nad']) #xóa hàng dựa trên giá trị cụ thể

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford


In [62]:
print(df.drop(df.index[1])) #xóa hàng dựa trên chỉ số

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford


In [63]:
print(df.drop(df.index[[1,2]])) #xóa nhiều hàng bằng cách sử dụng danh sách

            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford


In [64]:
print(df.drop(df.index[-2]))

              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Norway         Amy  2014        7     Oxford


In [65]:
#theo mặc định drop sẽ xóa hàng nhưng nếu xóa cột hãy sử dụng chỉ số 1
print(df.drop('reports', axis=1))

              name  year     school
Singapore    Janet  2012  Cambridge
China          Nad  2012     Oxford
Japan      Timothy  2013     Oxford
Sweden        June  2014  Cambridge
Norway         Amy  2014     Oxford


In [66]:
print(df.drop(df.columns[1], axis=1)) #dùng chỉ số

              name  reports     school
Singapore    Janet        6  Cambridge
China          Nad       13     Oxford
Japan      Timothy       14     Oxford
Sweden        June        1  Cambridge
Norway         Amy        7     Oxford


In [67]:
print(df.drop(df.columns[[1,3]], axis=1)) #danh sách

              name  reports
Singapore    Janet        6
China          Nad       13
Japan      Timothy       14
Sweden        June        1
Norway         Amy        7


In [68]:
#81
df = pd.DataFrame(
{
"Gender": ['Male','Male','Female','Female','Female'],
"Team" : [1,2,3,3,1]
})
print(df)

   Gender  Team
0    Male     1
1    Male     2
2  Female     3
3  Female     3
4  Female     1


In [69]:
print("Displaying the distribution of genders in each team")
print(pd.crosstab(df.Gender, df.Team)) #tao bảng tần xuất chéo giữa 2 cột

Displaying the distribution of genders in each team
Team    1  2  3
Gender         
Female  1  0  2
Male    1  1  0


In [70]:
print(pd.crosstab(df.Team, df.Gender)) #sự phân bố từng đội với từng giới tính

Gender  Female  Male
Team                
1            1     1
2            0     1
3            2     0
