In [1]:
import numpy as np

In [3]:
al = np.arange(10)#khoi tao mang 1 chieu gom cac phan tu 0 toi 9
print(al)
print(al.shape)#hinh dang cua mang 1 chieu 10 phan tu

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
a2 = np.arange(0, 10, 2)# khoi tao mang tu 0 toi 9 khoang cach 2
print(a2)

[0 2 4 6 8]


In [6]:
a3 = np.zeros(5) #khoi tao mang 5 phan tu la 0
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [7]:
a4 = np.zeros((2,3)) # khoi tao mang 2 chieu 2 hang 3 cot cac phan tu la 0
print(a4.shape)

(2, 3)


In [8]:
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
a5 = np.full((2, 3), 8) #khoi tao mang 2 chieu voi cac phan tu la 8

In [10]:
print(a5)

[[8 8 8]
 [8 8 8]]


In [11]:
a6 = np.eye(4)#tao 1 ma tran don vi

In [12]:
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
a7 = np.random.random((2, 4)) #tao ma tran 2 chieu ran dom cac gia tri chay tu 0 toi 1
print(a7)

[[0.83895117 0.79506925 0.16253835 0.54109846]
 [0.66302171 0.53985365 0.43658968 0.70500451]]


In [16]:
list1 = [1, 2, 3, 4, 5]

In [17]:
r1 = np.array(list1) #tao mang 1 chieu r1 voi noi dung cua danh sach lít1

In [18]:
print(r1)

[1 2 3 4 5]


In [19]:
print(r1[0])
print(r1[1])

1
2


In [20]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])  #tao mang 2 chieu tu list1, list2
print(r2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [21]:
print(r2.shape) # kich thuoc ma tran
print(r2[0,0]) # 1
print(r2[0,1]) # 2
print(r2[1,0])

(2, 5)
1
2
6


In [22]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1[[2,4]]) # in phan tu thu 2 va 4 trong mang bang cach goi danh sach

[3 5]


In [23]:
print(r1>2)#tra ve true khi phan tu trong mang >2

[False False  True  True  True]


In [24]:
print(r1[r1>2]) #tra ve nhung phan tu trong r1 thoa man >2

[3 4 5]


In [25]:
nums = np.arange(20)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
odd_num = nums[nums % 2 == 1] #mang chua nhung so le
print(odd_num) # [ 1 3 5 7 9 11 13 15 17 19]

[ 1  3  5  7  9 11 13 15 17 19]


In [27]:
a = np.array([[1,2,3,4,5],
[4,5,6,7,8],
[9,8,7,6,5]]) 
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [28]:
b1 = a[1:3, :3] #hang 1 tới 2, cot 0 tới 2
print(b1)

[[4 5 6]
 [9 8 7]]


In [29]:
b2 = a[-2:,-2:]  #in ra ma tran con bắt đầu từ hàng và cột -2 tới -1
print(b2)

[[7 8]
 [6 5]]


In [30]:
b3 = a[1: , 2:] #tran trận con tham chiếu tu hàng 1, cột 2 của ma trận a
print(b3)

[[6 7 8]
 [7 6 5]]


In [31]:
b3[0,2] =88 #gan gia tri cho phan tu[0,2] của mang b2 tương ứng với[1,4] ma tran a
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


In [32]:
b4 = a[2:, :] # từ hàng 2 và tất cả cột của ma trận a
print(b4)
print(b4.shape) #vì b4 được cắt theo kiểu 2 chiều nên shape sẽ in ra (hàng, cột)

[[9 8 7 6 5]]
(1, 5)


In [33]:
b5 = a[2, :] # cat hàng 2 và tất cả các cột
print(b5)

[9 8 7 6 5]


In [34]:
print(b5.shape) #vì b5 được hiểu cắt mảng 1 chiều nên shape sẽ in ra(phần tử,)

(5,)


In [35]:
b5 = b5.reshape(1,-1) #chuyển mảng 1 chiều thành 2 chiều với 1 hàng và số cột giữ nguyên so ban đầu
print(b5)

[[9 8 7 6 5]]


In [42]:
#chú ý chuyển đổi qua lại chiều của mảng phải thỏa mãn số phần tử bằng nhau
b4.reshape(-1,)

array([9, 8, 7, 6, 5])

In [43]:
x1 = np.array([[1,2,3],[4,5,6]]) #khoi tao mang 2 chieu tu danh sach
y1 = np.array([[7,8,9],[2,3,4]])

In [44]:
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


In [45]:
x = np.array([2,3])
y = np.array([4,2])
z = x + y

In [46]:
print(z)

[6 5]


In [47]:
print(x1 - y1) # same as np.subtract(x1,y1)

[[-6 -6 -6]
 [ 2  2  2]]


In [48]:
print(x1 * y1) # same as np.multiply(x1,y1)


[[ 7 16 27]
 [ 8 15 24]]


In [49]:
print(x1 / y1) # same as np.divide(x1,y1)

[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


In [2]:
#46
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

In [3]:
#47
bmi = weights/heights **2 # chỉ số cơ thể
print(bmi)

[28.88888889 14.51836889 23.046875  ]


In [52]:
print("Overweight: " , names[bmi>25])  #thua can
print("Underweight: " , names[bmi<18.5])  #thieu can
print("Healthy: " , names[(bmi>=18.5) & (bmi<=25)]) #binh thuong

Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']


In [53]:
#hàm dot là tinh tich vo huong cua 2 vector
x = np.array([2,3])
y = np.array([4,2])
np.dot(x,y) # 2x4 + 3x2 = 14

14

In [54]:
#48

In [55]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10], [11,12]])
print(np.dot(x2,y2)) #tich vo hương 2 ma trân 2x3 và 3x2
#vd: 1 × 7 + 2 × 9 + 3 × 11 = 58

[[ 58  64]
 [139 154]]


In [56]:
x2 = np.matrix([[1,2],[4,5]])  #giong mang tuy nhiên ma trận mặc định 2 chiều
y2 = np.matrix([[7,8],[2,3]])

In [57]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])
x1 = np.asmatrix(x1) # là 1 thu viện chuyển đổi mảng thành ma trận
y1 = np.asmatrix(y1)

In [58]:
x1 = np.array([[1,2],[4,5]])
y1 = np.array([[7,8],[2,3]])
print(x1 * y1)  #như nhân cac phân thử tương ứng của 2 mảng

[[ 7 16]
 [ 8 15]]


In [59]:
x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print(x2 * y2) #nhân 2 ma trận khác nhân 2 mảng, giống tích vô hướng 2 mảng(hàm dot)

[[11 14]
 [38 47]]


In [60]:
# tổng tích lũy
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
print(a.cumsum())

[ 1  3  6 10 15 21 28 36 45]


In [62]:
print(a.cumsum(axis=0)) #tổng tích lũy cột

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [63]:
print(a.cumsum(axis=1))  #tổng tích lũy hàng

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [64]:
#sắp xếp trong numpy

In [66]:
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages) # k tham chiếu tới địa chỉ mảng ban đầu
print(sorted_ages) 
print(ages)

[ 5 12 13 34 37]
[34 12 37  5 13]


In [67]:
ages.sort() # sửa đổi mảng
print(ages)

[ 5 12 13 34 37]


In [68]:
ages = np.array([34,12,37,5,13])
print(ages.argsort()) #trả về trị số của mảng trước đó sau khi đã đc sắp xếp

[3 1 4 0 2]


In [69]:
print(ages[ages.argsort()])

[ 5 12 13 34 37]


In [70]:
#51

In [71]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])

In [72]:
sort_indices = np.argsort(ages)

In [73]:
print(persons[sort_indices]) #sắp xếp người theo tuổi

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']


In [74]:
print(ages[sort_indices]) # [ 5 12 13 34 37]
print(heights[sort_indices])

[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


In [75]:
#tương tu có sắp xếp theo tên

In [76]:
sort_indices = np.argsort(persons)
print(persons[sort_indices])

['Joe' 'Johnny' 'Mary' 'Peter' 'Will']


In [77]:
print(ages[sort_indices])

[13 34 12 37  5]


In [78]:
print(heights[sort_indices])

[1.25 1.76 1.2  1.68 0.5 ]


In [79]:
#sắp xếp theop tên và đảo ngc thứ tự lại thành giảm dần
reverse_sort_indices = np.argsort(persons)[::-1]
print(persons[reverse_sort_indices])
print(ages[reverse_sort_indices])
print(heights[reverse_sort_indices])

['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
[ 5 37 12 34 13]
[0.5  1.68 1.2  1.76 1.25]


In [80]:
#52 gán mảng
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1) #sao chép theo tham chiếu
print(a1)


[[1 2 3 4]
 [5 6 7 8]]


In [81]:
a2 = a1 #sao chép bằng toán tử "="
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [83]:
#gán theo toán tử "=" thì a2 thực sự trỏ tới a1 vì vậy bất kì thay đổi nào 
#giữa 2 thằng đều làm thay đổi thằng còn lại
#vd:
a2[0][0] = 11 
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [84]:
#kể cả thay đổi định hình của 1 mảng thì mảng còn lại cũng bị thay đổi theo

In [85]:
a1.shape = 1,-1 # reshape a1
print(a1)

[[11  2  3  4  5  6  7  8]]


In [86]:
print(a2) #a2 cùng bị thay đổi

[[11  2  3  4  5  6  7  8]]


In [87]:
#54
#tao bản sao , khi thay đổi định dạng bản gốc bản sao vẫn giữ nguyên ban đầu so 
#với bản sao trước đó, còn thay đổi giá trị thì vẫn bị thay đổi
a2 = a1.view()

In [88]:
print(a1)


[[11  2  3  4  5  6  7  8]]


In [89]:
print(a2)

[[11  2  3  4  5  6  7  8]]


In [90]:
a1[0][0] = 11 # thay đổi giá trị
print(a1)

[[11  2  3  4  5  6  7  8]]


In [91]:
print(a2)

[[11  2  3  4  5  6  7  8]]


In [92]:
#thay đổi định dạng

In [93]:
a1.shape = 1,-1
print(a1)

[[11  2  3  4  5  6  7  8]]


In [96]:
a1.shape = -1,4
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [97]:
print(a2)

[[11  2  3  4  5  6  7  8]]


In [105]:
#sao chép theo giá trị 
#55
#hàm copy, đây là sao chép sâu tức khi bản gốc thay đổi bất kể về giá trị hay
#định dạng thì bản sao vẫn không ảnh hưởng

In [99]:
#vd:

In [100]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
a2 = a1.copy()

In [101]:
a1[0][0] = 11 # make some changes in a1
print(a1)

[[11  2  3  4]
 [ 5  6  7  8]]


In [102]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [103]:
a1.shape = 1,-1 # change the shape of a1
print(a1)

[[11  2  3  4  5  6  7  8]]


In [104]:
print(a2)

[[1 2 3 4]
 [5 6 7 8]]
